name: MATLAB Unit Tests

on: push



jobs:
  test:
    name: Run MATLAB Unit Tests
    runs-on: ubuntu-latest   # Use the latest Ubuntu runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3   # Check out the repository code

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2   # Set up MATLAB on the runner
        with:
          release: latest

      - name: Run MATLAB tests
        uses: matlab-actions/run-tests@v2    # Run the tests in the MATLAB file
        

